//
//  DemoDataProvider.swift
//  HarvestQRBill
//

import Foundation

#if DEBUG
enum DemoDataProvider {
    static var invoices: [Invoice] {
        let now = Date()
        let day: TimeInterval = 86400

        return [
            Invoice(
                id: 1001,
                clientKey: "demo-001",
                number: "INV-2024-042",
                purchaseOrder: nil,
                amount: 4250.00,
                dueAmount: 4250.00,
                tax: 8.1,
                taxAmount: 344.25,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Website Redesign",
                notes: "Vielen Dank für Ihren Auftrag.",
                currency: "CHF",
                state: .open,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-7 * day),
                dueDate: now.addingTimeInterval(23 * day),
                sentAt: now.addingTimeInterval(-6 * day),
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-7 * day),
                updatedAt: now.addingTimeInterval(-7 * day),
                client: ClientReference(id: 1, name: "Agency for Design and Art"),
                lineItems: [
                    LineItem(id: 1, kind: "Service", description: "UX Design & Konzept", quantity: 16, unitPrice: 150.00, amount: 2400.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 2, kind: "Service", description: "Frontend Development", quantity: 12, unitPrice: 150.00, amount: 1800.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 3, kind: "Product", description: "Hosting Setup", quantity: 1, unitPrice: 50.00, amount: 50.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1002,
                clientKey: "demo-002",
                number: "INV-2024-041",
                purchaseOrder: nil,
                amount: 1875.00,
                dueAmount: 0,
                tax: 8.1,
                taxAmount: 151.88,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Branding Package",
                notes: nil,
                currency: "CHF",
                state: .paid,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-35 * day),
                dueDate: now.addingTimeInterval(-5 * day),
                sentAt: now.addingTimeInterval(-34 * day),
                paidAt: now.addingTimeInterval(-12 * day),
                paidDate: now.addingTimeInterval(-12 * day),
                closedAt: nil,
                createdAt: now.addingTimeInterval(-35 * day),
                updatedAt: now.addingTimeInterval(-12 * day),
                client: ClientReference(id: 2, name: "Ipsum"),
                lineItems: [
                    LineItem(id: 4, kind: "Service", description: "Logo Design", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 5, kind: "Service", description: "Styleguide", quantity: 4.5, unitPrice: 150.00, amount: 675.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1003,
                clientKey: "demo-003",
                number: "INV-2024-040",
                purchaseOrder: "PO-2024-789",
                amount: 8500.00,
                dueAmount: 8500.00,
                tax: 8.1,
                taxAmount: 688.50,
                tax2: nil,
                tax2Amount: nil,
                discount: 5,
                discountAmount: 425.00,
                subject: "App Development Phase 1",
                notes: "Zahlung innert 30 Tagen.",
                currency: "CHF",
                state: .open,
                periodStart: now.addingTimeInterval(-60 * day),
                periodEnd: now.addingTimeInterval(-30 * day),
                issueDate: now.addingTimeInterval(-14 * day),
                dueDate: now.addingTimeInterval(16 * day),
                sentAt: now.addingTimeInterval(-13 * day),
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-14 * day),
                updatedAt: now.addingTimeInterval(-14 * day),
                client: ClientReference(id: 3, name: "Agentur für Sein und Haben"),
                lineItems: [
                    LineItem(id: 6, kind: "Service", description: "iOS Development", quantity: 40, unitPrice: 160.00, amount: 6400.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 7, kind: "Service", description: "UI Design", quantity: 12, unitPrice: 150.00, amount: 1800.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 8, kind: "Service", description: "Project Management", quantity: 2, unitPrice: 150.00, amount: 300.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1004,
                clientKey: "demo-004",
                number: "INV-2024-039",
                purchaseOrder: nil,
                amount: 2340.00,
                dueAmount: 0,
                tax: 8.1,
                taxAmount: 189.54,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Social Media Assets",
                notes: nil,
                currency: "CHF",
                state: .paid,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-45 * day),
                dueDate: now.addingTimeInterval(-15 * day),
                sentAt: now.addingTimeInterval(-44 * day),
                paidAt: now.addingTimeInterval(-20 * day),
                paidDate: now.addingTimeInterval(-20 * day),
                closedAt: nil,
                createdAt: now.addingTimeInterval(-45 * day),
                updatedAt: now.addingTimeInterval(-20 * day),
                client: ClientReference(id: 4, name: "Büro für Haben und Zins"),
                lineItems: [
                    LineItem(id: 9, kind: "Service", description: "Design Templates", quantity: 12, unitPrice: 120.00, amount: 1440.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 10, kind: "Service", description: "Asset Production", quantity: 6, unitPrice: 150.00, amount: 900.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1005,
                clientKey: "demo-005",
                number: "INV-2024-043",
                purchaseOrder: nil,
                amount: 3600.00,
                dueAmount: 3600.00,
                tax: 8.1,
                taxAmount: 291.60,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Corporate Identity",
                notes: nil,
                currency: "CHF",
                state: .draft,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now,
                dueDate: now.addingTimeInterval(30 * day),
                sentAt: nil,
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now,
                updatedAt: now,
                client: ClientReference(id: 5, name: "Studio für Zins und Design"),
                lineItems: [
                    LineItem(id: 11, kind: "Service", description: "Brand Strategy Workshop", quantity: 8, unitPrice: 200.00, amount: 1600.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 12, kind: "Service", description: "Visual Identity Design", quantity: 12, unitPrice: 150.00, amount: 1800.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 13, kind: "Product", description: "Brand Guidelines PDF", quantity: 1, unitPrice: 200.00, amount: 200.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1006,
                clientKey: "demo-006",
                number: "INV-2024-038",
                purchaseOrder: nil,
                amount: 1200.00,
                dueAmount: 0,
                tax: 8.1,
                taxAmount: 97.20,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Consulting",
                notes: "Danke für die gute Zusammenarbeit!",
                currency: "CHF",
                state: .closed,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-90 * day),
                dueDate: now.addingTimeInterval(-60 * day),
                sentAt: now.addingTimeInterval(-89 * day),
                paidAt: now.addingTimeInterval(-65 * day),
                paidDate: now.addingTimeInterval(-65 * day),
                closedAt: now.addingTimeInterval(-60 * day),
                createdAt: now.addingTimeInterval(-90 * day),
                updatedAt: now.addingTimeInterval(-60 * day),
                client: ClientReference(id: 2, name: "Ipsum"),
                lineItems: [
                    LineItem(id: 14, kind: "Service", description: "Strategy Consulting", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1007,
                clientKey: "demo-007",
                number: "INV-2024-044",
                purchaseOrder: nil,
                amount: 5750.00,
                dueAmount: 5750.00,
                tax: 8.1,
                taxAmount: 465.75,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "E-Commerce Platform",
                notes: nil,
                currency: "CHF",
                state: .open,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-3 * day),
                dueDate: now.addingTimeInterval(27 * day),
                sentAt: now.addingTimeInterval(-2 * day),
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-3 * day),
                updatedAt: now.addingTimeInterval(-3 * day),
                client: ClientReference(id: 1, name: "Agency for Design and Art"),
                lineItems: [
                    LineItem(id: 15, kind: "Service", description: "Shopify Setup", quantity: 20, unitPrice: 150.00, amount: 3000.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 16, kind: "Service", description: "Theme Customization", quantity: 15, unitPrice: 150.00, amount: 2250.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 17, kind: "Product", description: "Domain & SSL", quantity: 1, unitPrice: 500.00, amount: 500.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            // Additional drafts
            Invoice(
                id: 1008,
                clientKey: "demo-008",
                number: "INV-2024-045",
                purchaseOrder: nil,
                amount: 2400.00,
                dueAmount: 2400.00,
                tax: 8.1,
                taxAmount: 194.40,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Newsletter Design",
                notes: nil,
                currency: "CHF",
                state: .draft,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now,
                dueDate: now.addingTimeInterval(30 * day),
                sentAt: nil,
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-1 * day),
                updatedAt: now,
                client: ClientReference(id: 6, name: "Werkstatt Müller AG"),
                lineItems: [
                    LineItem(id: 18, kind: "Service", description: "Email Template Design", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 19, kind: "Service", description: "Automation Setup", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1009,
                clientKey: "demo-009",
                number: "INV-2024-046",
                purchaseOrder: nil,
                amount: 950.00,
                dueAmount: 950.00,
                tax: 8.1,
                taxAmount: 76.95,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Logo Refresh",
                notes: "Entwurf noch in Bearbeitung.",
                currency: "CHF",
                state: .draft,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now,
                dueDate: now.addingTimeInterval(30 * day),
                sentAt: nil,
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-2 * day),
                updatedAt: now,
                client: ClientReference(id: 3, name: "Agentur für Sein und Haben"),
                lineItems: [
                    LineItem(id: 20, kind: "Service", description: "Logo Redesign", quantity: 5, unitPrice: 150.00, amount: 750.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 21, kind: "Product", description: "Vector Files", quantity: 1, unitPrice: 200.00, amount: 200.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1010,
                clientKey: "demo-010",
                number: "INV-2024-047",
                purchaseOrder: "PO-2024-901",
                amount: 12500.00,
                dueAmount: 12500.00,
                tax: 8.1,
                taxAmount: 1012.50,
                tax2: nil,
                tax2Amount: nil,
                discount: 10,
                discountAmount: 1250.00,
                subject: "Mobile App Phase 2",
                notes: nil,
                currency: "CHF",
                state: .draft,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now,
                dueDate: now.addingTimeInterval(30 * day),
                sentAt: nil,
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now,
                updatedAt: now,
                client: ClientReference(id: 7, name: "Innovate Schweiz GmbH"),
                lineItems: [
                    LineItem(id: 22, kind: "Service", description: "iOS Development", quantity: 50, unitPrice: 160.00, amount: 8000.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 23, kind: "Service", description: "Android Development", quantity: 25, unitPrice: 160.00, amount: 4000.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 24, kind: "Service", description: "QA Testing", quantity: 5, unitPrice: 100.00, amount: 500.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            // Older paid invoices
            Invoice(
                id: 1011,
                clientKey: "demo-011",
                number: "INV-2024-037",
                purchaseOrder: nil,
                amount: 3200.00,
                dueAmount: 0,
                tax: 8.1,
                taxAmount: 259.20,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Print Campaign",
                notes: nil,
                currency: "CHF",
                state: .paid,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-120 * day),
                dueDate: now.addingTimeInterval(-90 * day),
                sentAt: now.addingTimeInterval(-119 * day),
                paidAt: now.addingTimeInterval(-95 * day),
                paidDate: now.addingTimeInterval(-95 * day),
                closedAt: nil,
                createdAt: now.addingTimeInterval(-120 * day),
                updatedAt: now.addingTimeInterval(-95 * day),
                client: ClientReference(id: 4, name: "Büro für Haben und Zins"),
                lineItems: [
                    LineItem(id: 25, kind: "Service", description: "Flyer Design", quantity: 6, unitPrice: 150.00, amount: 900.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 26, kind: "Service", description: "Poster Design", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 27, kind: "Service", description: "Print Production", quantity: 1, unitPrice: 1100.00, amount: 1100.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1012,
                clientKey: "demo-012",
                number: "INV-2024-036",
                purchaseOrder: nil,
                amount: 4800.00,
                dueAmount: 0,
                tax: 8.1,
                taxAmount: 388.80,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Website Maintenance Q1",
                notes: "Wartungsvertrag Januar - März 2024",
                currency: "CHF",
                state: .closed,
                periodStart: now.addingTimeInterval(-180 * day),
                periodEnd: now.addingTimeInterval(-90 * day),
                issueDate: now.addingTimeInterval(-150 * day),
                dueDate: now.addingTimeInterval(-120 * day),
                sentAt: now.addingTimeInterval(-149 * day),
                paidAt: now.addingTimeInterval(-125 * day),
                paidDate: now.addingTimeInterval(-125 * day),
                closedAt: now.addingTimeInterval(-120 * day),
                createdAt: now.addingTimeInterval(-150 * day),
                updatedAt: now.addingTimeInterval(-120 * day),
                client: ClientReference(id: 1, name: "Agency for Design and Art"),
                lineItems: [
                    LineItem(id: 28, kind: "Service", description: "Monthly Maintenance", quantity: 3, unitPrice: 800.00, amount: 2400.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 29, kind: "Service", description: "Security Updates", quantity: 12, unitPrice: 100.00, amount: 1200.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 30, kind: "Service", description: "Content Updates", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1013,
                clientKey: "demo-013",
                number: "INV-2023-089",
                purchaseOrder: nil,
                amount: 6750.00,
                dueAmount: 0,
                tax: 7.7,
                taxAmount: 519.75,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Annual Report Design",
                notes: nil,
                currency: "CHF",
                state: .closed,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-300 * day),
                dueDate: now.addingTimeInterval(-270 * day),
                sentAt: now.addingTimeInterval(-299 * day),
                paidAt: now.addingTimeInterval(-275 * day),
                paidDate: now.addingTimeInterval(-275 * day),
                closedAt: now.addingTimeInterval(-270 * day),
                createdAt: now.addingTimeInterval(-300 * day),
                updatedAt: now.addingTimeInterval(-270 * day),
                client: ClientReference(id: 8, name: "Helvetia Treuhand"),
                lineItems: [
                    LineItem(id: 31, kind: "Service", description: "Layout Design", quantity: 25, unitPrice: 150.00, amount: 3750.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 32, kind: "Service", description: "Infographics", quantity: 12, unitPrice: 200.00, amount: 2400.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 33, kind: "Product", description: "Print-ready PDF", quantity: 1, unitPrice: 600.00, amount: 600.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1014,
                clientKey: "demo-014",
                number: "INV-2023-088",
                purchaseOrder: nil,
                amount: 1500.00,
                dueAmount: 0,
                tax: 7.7,
                taxAmount: 115.50,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Photography Session",
                notes: "Team portraits for website.",
                currency: "CHF",
                state: .paid,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-320 * day),
                dueDate: now.addingTimeInterval(-290 * day),
                sentAt: now.addingTimeInterval(-319 * day),
                paidAt: now.addingTimeInterval(-300 * day),
                paidDate: now.addingTimeInterval(-300 * day),
                closedAt: nil,
                createdAt: now.addingTimeInterval(-320 * day),
                updatedAt: now.addingTimeInterval(-300 * day),
                client: ClientReference(id: 2, name: "Ipsum"),
                lineItems: [
                    LineItem(id: 34, kind: "Service", description: "Photo Session", quantity: 4, unitPrice: 250.00, amount: 1000.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 35, kind: "Service", description: "Post-processing", quantity: 2.5, unitPrice: 200.00, amount: 500.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1015,
                clientKey: "demo-015",
                number: "INV-2023-087",
                purchaseOrder: "PO-2023-456",
                amount: 15000.00,
                dueAmount: 0,
                tax: 7.7,
                taxAmount: 1155.00,
                tax2: nil,
                tax2Amount: nil,
                discount: 5,
                discountAmount: 750.00,
                subject: "Brand Launch Campaign",
                notes: nil,
                currency: "CHF",
                state: .closed,
                periodStart: now.addingTimeInterval(-400 * day),
                periodEnd: now.addingTimeInterval(-350 * day),
                issueDate: now.addingTimeInterval(-350 * day),
                dueDate: now.addingTimeInterval(-320 * day),
                sentAt: now.addingTimeInterval(-349 * day),
                paidAt: now.addingTimeInterval(-325 * day),
                paidDate: now.addingTimeInterval(-325 * day),
                closedAt: now.addingTimeInterval(-320 * day),
                createdAt: now.addingTimeInterval(-350 * day),
                updatedAt: now.addingTimeInterval(-320 * day),
                client: ClientReference(id: 7, name: "Innovate Schweiz GmbH"),
                lineItems: [
                    LineItem(id: 36, kind: "Service", description: "Campaign Strategy", quantity: 20, unitPrice: 200.00, amount: 4000.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 37, kind: "Service", description: "Creative Development", quantity: 40, unitPrice: 150.00, amount: 6000.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 38, kind: "Service", description: "Media Production", quantity: 25, unitPrice: 160.00, amount: 4000.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 39, kind: "Product", description: "Ad Placements", quantity: 1, unitPrice: 1000.00, amount: 1000.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            // Overdue invoice
            Invoice(
                id: 1016,
                clientKey: "demo-016",
                number: "INV-2024-035",
                purchaseOrder: nil,
                amount: 2100.00,
                dueAmount: 2100.00,
                tax: 8.1,
                taxAmount: 170.10,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Video Editing",
                notes: "Zweite Mahnung versendet.",
                currency: "CHF",
                state: .open,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-60 * day),
                dueDate: now.addingTimeInterval(-30 * day),
                sentAt: now.addingTimeInterval(-59 * day),
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-60 * day),
                updatedAt: now.addingTimeInterval(-15 * day),
                client: ClientReference(id: 9, name: "Kreativ Studio Basel"),
                lineItems: [
                    LineItem(id: 40, kind: "Service", description: "Video Editing", quantity: 10, unitPrice: 140.00, amount: 1400.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 41, kind: "Service", description: "Color Grading", quantity: 3.5, unitPrice: 200.00, amount: 700.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            // More older closed invoices
            Invoice(
                id: 1017,
                clientKey: "demo-017",
                number: "INV-2023-086",
                purchaseOrder: nil,
                amount: 880.00,
                dueAmount: 0,
                tax: 7.7,
                taxAmount: 67.76,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Icon Set Design",
                notes: nil,
                currency: "CHF",
                state: .paid,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-380 * day),
                dueDate: now.addingTimeInterval(-350 * day),
                sentAt: now.addingTimeInterval(-379 * day),
                paidAt: now.addingTimeInterval(-360 * day),
                paidDate: now.addingTimeInterval(-360 * day),
                closedAt: nil,
                createdAt: now.addingTimeInterval(-380 * day),
                updatedAt: now.addingTimeInterval(-360 * day),
                client: ClientReference(id: 5, name: "Studio für Zins und Design"),
                lineItems: [
                    LineItem(id: 42, kind: "Service", description: "Icon Design", quantity: 4, unitPrice: 120.00, amount: 480.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 43, kind: "Product", description: "SVG Icon Pack", quantity: 1, unitPrice: 400.00, amount: 400.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1018,
                clientKey: "demo-018",
                number: "INV-2023-085",
                purchaseOrder: nil,
                amount: 5400.00,
                dueAmount: 0,
                tax: 7.7,
                taxAmount: 415.80,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "UX Audit & Recommendations",
                notes: nil,
                currency: "CHF",
                state: .closed,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-420 * day),
                dueDate: now.addingTimeInterval(-390 * day),
                sentAt: now.addingTimeInterval(-419 * day),
                paidAt: now.addingTimeInterval(-395 * day),
                paidDate: now.addingTimeInterval(-395 * day),
                closedAt: now.addingTimeInterval(-390 * day),
                createdAt: now.addingTimeInterval(-420 * day),
                updatedAt: now.addingTimeInterval(-390 * day),
                client: ClientReference(id: 8, name: "Helvetia Treuhand"),
                lineItems: [
                    LineItem(id: 44, kind: "Service", description: "UX Audit", quantity: 16, unitPrice: 180.00, amount: 2880.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 45, kind: "Service", description: "User Testing", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 46, kind: "Service", description: "Report & Presentation", quantity: 8, unitPrice: 165.00, amount: 1320.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            // Another draft
            Invoice(
                id: 1019,
                clientKey: "demo-019",
                number: "INV-2024-048",
                purchaseOrder: nil,
                amount: 1800.00,
                dueAmount: 1800.00,
                tax: 8.1,
                taxAmount: 145.80,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Social Media Strategy",
                notes: nil,
                currency: "CHF",
                state: .draft,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now,
                dueDate: now.addingTimeInterval(30 * day),
                sentAt: nil,
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-3 * day),
                updatedAt: now,
                client: ClientReference(id: 6, name: "Werkstatt Müller AG"),
                lineItems: [
                    LineItem(id: 47, kind: "Service", description: "Strategy Development", quantity: 6, unitPrice: 200.00, amount: 1200.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 48, kind: "Service", description: "Content Calendar", quantity: 4, unitPrice: 150.00, amount: 600.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1020,
                clientKey: "demo-020",
                number: "INV-2023-084",
                purchaseOrder: nil,
                amount: 3150.00,
                dueAmount: 0,
                tax: 7.7,
                taxAmount: 242.55,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Packaging Design",
                notes: nil,
                currency: "CHF",
                state: .paid,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-450 * day),
                dueDate: now.addingTimeInterval(-420 * day),
                sentAt: now.addingTimeInterval(-449 * day),
                paidAt: now.addingTimeInterval(-430 * day),
                paidDate: now.addingTimeInterval(-430 * day),
                closedAt: nil,
                createdAt: now.addingTimeInterval(-450 * day),
                updatedAt: now.addingTimeInterval(-430 * day),
                client: ClientReference(id: 9, name: "Kreativ Studio Basel"),
                lineItems: [
                    LineItem(id: 49, kind: "Service", description: "Packaging Concept", quantity: 10, unitPrice: 150.00, amount: 1500.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 50, kind: "Service", description: "3D Mockups", quantity: 6, unitPrice: 175.00, amount: 1050.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 51, kind: "Product", description: "Print Files", quantity: 1, unitPrice: 600.00, amount: 600.00, taxed: true, taxed2: false, project: nil)
                ]
            )
        ]
    }

    static var defaultCreditorInfo: CreditorInfo {
        CreditorInfo(
            iban: "CH93 0076 2011 6238 5295 7",
            name: "Demo Company GmbH",
            streetName: "Bahnhofstrasse",
            buildingNumber: "42",
            postalCode: "8001",
            town: "Zürich",
            country: "CH"
        )
    }
}
#endif
