//
//  DemoDataProvider.swift
//  Harvester
//

import Foundation

enum DemoDataProvider {
    static var invoices: [Invoice] {
        let now = Date()
        let day: TimeInterval = 86400

        return [
            Invoice(
                id: 1001,
                clientKey: "demo-001",
                number: "INV-2024-042",
                purchaseOrder: nil,
                amount: 4250.00,
                dueAmount: 4250.00,
                tax: 8.1,
                taxAmount: 344.25,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Website Redesign",
                notes: "Vielen Dank für Ihren Auftrag.",
                currency: "CHF",
                state: .open,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-7 * day),
                dueDate: now.addingTimeInterval(23 * day),
                sentAt: now.addingTimeInterval(-6 * day),
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-7 * day),
                updatedAt: now.addingTimeInterval(-7 * day),
                client: ClientReference(id: 1, name: "Agency for Design and Art"),
                lineItems: [
                    LineItem(id: 1, kind: "Service", description: "UX Design & Konzept", quantity: 16, unitPrice: 150.00, amount: 2400.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 2, kind: "Service", description: "Frontend Development", quantity: 12, unitPrice: 150.00, amount: 1800.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 3, kind: "Product", description: "Hosting Setup", quantity: 1, unitPrice: 50.00, amount: 50.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1002,
                clientKey: "demo-002",
                number: "INV-2024-041",
                purchaseOrder: nil,
                amount: 1875.00,
                dueAmount: 0,
                tax: 8.1,
                taxAmount: 151.88,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Branding Package",
                notes: nil,
                currency: "CHF",
                state: .paid,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-35 * day),
                dueDate: now.addingTimeInterval(-5 * day),
                sentAt: now.addingTimeInterval(-34 * day),
                paidAt: now.addingTimeInterval(-12 * day),
                paidDate: now.addingTimeInterval(-12 * day),
                closedAt: nil,
                createdAt: now.addingTimeInterval(-35 * day),
                updatedAt: now.addingTimeInterval(-12 * day),
                client: ClientReference(id: 2, name: "Ipsum"),
                lineItems: [
                    LineItem(id: 4, kind: "Service", description: "Logo Design", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 5, kind: "Service", description: "Styleguide", quantity: 4.5, unitPrice: 150.00, amount: 675.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1003,
                clientKey: "demo-003",
                number: "INV-2024-040",
                purchaseOrder: "PO-2024-789",
                amount: 8500.00,
                dueAmount: 8500.00,
                tax: 8.1,
                taxAmount: 688.50,
                tax2: nil,
                tax2Amount: nil,
                discount: 5,
                discountAmount: 425.00,
                subject: "App Development Phase 1",
                notes: "Zahlung innert 30 Tagen.",
                currency: "CHF",
                state: .open,
                periodStart: now.addingTimeInterval(-60 * day),
                periodEnd: now.addingTimeInterval(-30 * day),
                issueDate: now.addingTimeInterval(-14 * day),
                dueDate: now.addingTimeInterval(16 * day),
                sentAt: now.addingTimeInterval(-13 * day),
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-14 * day),
                updatedAt: now.addingTimeInterval(-14 * day),
                client: ClientReference(id: 3, name: "Agentur für Sein und Haben"),
                lineItems: [
                    LineItem(id: 6, kind: "Service", description: "iOS Development", quantity: 40, unitPrice: 160.00, amount: 6400.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 7, kind: "Service", description: "UI Design", quantity: 12, unitPrice: 150.00, amount: 1800.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 8, kind: "Service", description: "Project Management", quantity: 2, unitPrice: 150.00, amount: 300.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1004,
                clientKey: "demo-004",
                number: "INV-2024-039",
                purchaseOrder: nil,
                amount: 2340.00,
                dueAmount: 0,
                tax: 8.1,
                taxAmount: 189.54,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Social Media Assets",
                notes: nil,
                currency: "CHF",
                state: .paid,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-45 * day),
                dueDate: now.addingTimeInterval(-15 * day),
                sentAt: now.addingTimeInterval(-44 * day),
                paidAt: now.addingTimeInterval(-20 * day),
                paidDate: now.addingTimeInterval(-20 * day),
                closedAt: nil,
                createdAt: now.addingTimeInterval(-45 * day),
                updatedAt: now.addingTimeInterval(-20 * day),
                client: ClientReference(id: 4, name: "Büro für Haben und Zins"),
                lineItems: [
                    LineItem(id: 9, kind: "Service", description: "Design Templates", quantity: 12, unitPrice: 120.00, amount: 1440.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 10, kind: "Service", description: "Asset Production", quantity: 6, unitPrice: 150.00, amount: 900.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1005,
                clientKey: "demo-005",
                number: "INV-2024-043",
                purchaseOrder: nil,
                amount: 3600.00,
                dueAmount: 3600.00,
                tax: 8.1,
                taxAmount: 291.60,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Corporate Identity",
                notes: nil,
                currency: "CHF",
                state: .draft,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now,
                dueDate: now.addingTimeInterval(30 * day),
                sentAt: nil,
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now,
                updatedAt: now,
                client: ClientReference(id: 5, name: "Studio für Zins und Design"),
                lineItems: [
                    LineItem(id: 11, kind: "Service", description: "Brand Strategy Workshop", quantity: 8, unitPrice: 200.00, amount: 1600.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 12, kind: "Service", description: "Visual Identity Design", quantity: 12, unitPrice: 150.00, amount: 1800.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 13, kind: "Product", description: "Brand Guidelines PDF", quantity: 1, unitPrice: 200.00, amount: 200.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1006,
                clientKey: "demo-006",
                number: "INV-2024-038",
                purchaseOrder: nil,
                amount: 1200.00,
                dueAmount: 0,
                tax: 8.1,
                taxAmount: 97.20,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "Consulting",
                notes: "Danke für die gute Zusammenarbeit!",
                currency: "CHF",
                state: .closed,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-90 * day),
                dueDate: now.addingTimeInterval(-60 * day),
                sentAt: now.addingTimeInterval(-89 * day),
                paidAt: now.addingTimeInterval(-65 * day),
                paidDate: now.addingTimeInterval(-65 * day),
                closedAt: now.addingTimeInterval(-60 * day),
                createdAt: now.addingTimeInterval(-90 * day),
                updatedAt: now.addingTimeInterval(-60 * day),
                client: ClientReference(id: 2, name: "Ipsum"),
                lineItems: [
                    LineItem(id: 14, kind: "Service", description: "Strategy Consulting", quantity: 8, unitPrice: 150.00, amount: 1200.00, taxed: true, taxed2: false, project: nil)
                ]
            ),
            Invoice(
                id: 1007,
                clientKey: "demo-007",
                number: "INV-2024-044",
                purchaseOrder: nil,
                amount: 5750.00,
                dueAmount: 5750.00,
                tax: 8.1,
                taxAmount: 465.75,
                tax2: nil,
                tax2Amount: nil,
                discount: nil,
                discountAmount: nil,
                subject: "E-Commerce Platform",
                notes: nil,
                currency: "CHF",
                state: .open,
                periodStart: nil,
                periodEnd: nil,
                issueDate: now.addingTimeInterval(-3 * day),
                dueDate: now.addingTimeInterval(27 * day),
                sentAt: now.addingTimeInterval(-2 * day),
                paidAt: nil,
                paidDate: nil,
                closedAt: nil,
                createdAt: now.addingTimeInterval(-3 * day),
                updatedAt: now.addingTimeInterval(-3 * day),
                client: ClientReference(id: 1, name: "Agency for Design and Art"),
                lineItems: [
                    LineItem(id: 15, kind: "Service", description: "Shopify Setup", quantity: 20, unitPrice: 150.00, amount: 3000.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 16, kind: "Service", description: "Theme Customization", quantity: 15, unitPrice: 150.00, amount: 2250.00, taxed: true, taxed2: false, project: nil),
                    LineItem(id: 17, kind: "Product", description: "Domain & SSL", quantity: 1, unitPrice: 500.00, amount: 500.00, taxed: true, taxed2: false, project: nil)
                ]
            )
        ]
    }

    static var defaultCreditorInfo: CreditorInfo {
        CreditorInfo(
            iban: "CH93 0076 2011 6238 5295 7",
            name: "Demo Company GmbH",
            streetName: "Bahnhofstrasse",
            buildingNumber: "42",
            postalCode: "8001",
            town: "Zürich",
            country: "CH"
        )
    }
}
